@startuml
package Loader {
	package CLI
}

package PEBL {
	package Mapping
	package Aggregator
}
package BPMNviz
package Yaoqiang.BPMN.Editor
CLI --> Mapping
CLI --> BPMNviz
Aggregator -> Mapping
CLI --> Aggregator
BPMNviz --> Yaoqiang.BPMN.Editor

hide empty members
hide empty methods
hide circle

skinparam monochrome true
skinparam shadowing false
skinparam packageStyle rect
@enduml
