package peal;

public enum InstanceStateDetailed {
    PROCESS_INSTANCE_ABORTED,
    PROCESS_INSTANCE_ABORTED_BECAUSE_ERROR_EVENT_THROWN,
    PROCESS_INSTANCE_ABORTED_BECAUSE_ESCALATION_EVENT_THROWN,
    COULD_NOT_CHECK_PROCESS_INSTANCE_STATUS,
    OK,
    UNKNOWN,
    UNDEPLOYED_PROCESS,
    RUNTIME
}
