@startuml

package PEBL {
	package Mapping
	package Aggregator
	package Validation
}

package EclipseLink {
	package Moxy
}

package BPELlint
package BPMNspector
Mapping -> Moxy

Aggregator -> Mapping
Validation -left-> Mapping
Validation -> BPELlint
Validation -> BPMNspector
hide empty members
hide empty methods
hide circle

skinparam monochrome true
skinparam shadowing false
skinparam packageStyle rect
@enduml
