
package de.uniba.wiai.dsg.bpel_engine_comparison.activities.wsdl.testpartner;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TestPartnerPortType", targetNamespace = "http://dsg.wiai.uniba.de/betsy/activities/wsdl/testpartner")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TestPartnerPortType {


    /**
     * 
     * @param inputPart
     */
    @WebMethod
    @Oneway
    public void startProcessAsync(
            @WebParam(name = "testElementAsyncRequest", targetNamespace = "http://dsg.wiai.uniba.de/betsy/activities/wsdl/testpartner", partName = "inputPart")
            int inputPart);

    /**
     * 
     * @param inputPart
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "testElementSyncResponse", targetNamespace = "http://dsg.wiai.uniba.de/betsy/activities/wsdl/testpartner", partName = "outputPart")
    public int startProcessSync(
            @WebParam(name = "testElementSyncRequest", targetNamespace = "http://dsg.wiai.uniba.de/betsy/activities/wsdl/testpartner", partName = "inputPart")
            int inputPart);

    /**
     * 
     */
    @WebMethod
    @Oneway
    public void startProcessWithEmptyMessage();

}
