@startuml
package ant
package maven
package engines

package PEAL {
	package IMPL
	package API

	API -> IMPL
	IMPL -> ant
	IMPL -> maven
	IMPL -> engines
}


hide empty members
hide empty methods
hide circle

skinparam monochrome true
skinparam shadowing false
skinparam packageStyle rect
@enduml
