
package de.uniba.wiai.dsg.betsy.activities.wsdl.testpartner;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "testElementFault", targetNamespace = "http://dsg.wiai.uniba.de/betsy/activities/wsdl/testpartner")
public class FaultMessage
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private int faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public FaultMessage(String message, int faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public FaultMessage(String message, int faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: int
     */
    public int getFaultInfo() {
        return faultInfo;
    }

}
