@startuml

class VirtualMachineService {
  start() : void
  kill() : void
  restore() : void
  getState() : VirtualMachineState
}

class VirtualMachineState {
  OFF
  SAVED
  ACTIVE
}

hide empty members
hide empty methods
hide circle

skinparam monochrome true
skinparam shadowing false
skinparam packageStyle rect
@enduml
