@startuml
interface AggregateScript {
    aggregate(List<TestResult>) : String
}

interface StepScript {
	execute(TestCase) : void
}

interface AssertionScript {
	check(TestCase) : void {AssertionError}
}

AggregateScript -[hidden]right- StepScript
StepScript -[hidden]right- AssertionScript


hide empty members
hide empty methods
hide circle

skinparam monochrome true
skinparam shadowing false
skinparam packageStyle rect
@enduml
