<?xml version="1.0" encoding="UTF-8"?>
<definitions name="TestInterface"
             targetNamespace="http://dsg.wiai.uniba.de/betsy/activities/wsdl/testinterface"
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <types>
        <xsd:schema targetNamespace="http://xml.netbeans.org/schema/CalculatorSchema">
            <xsd:redefine schemaLocation="CalculatorSchema_WithSimpleTypeGroupAndAttributeGroup.xsd">
                <xsd:group name="myCustomGroup">
                    <xsd:sequence>
                        <xsd:element name="myElement" type="xsd:int"/>
                    </xsd:sequence>
                </xsd:group>
            </xsd:redefine>
        </xsd:schema>
    </types>

</definitions>
